### ISSUE TITLE
KeyError with "optimade init" and "optimade run"

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-optimade#126]
I just tried to initialize the OPTIMADE server with a vanilla AiiDA profile called "optimade" and encountered the following error:
```
$ aiida-optimade -p optimade init
/home/sadorf/miniconda3/envs/aiida-optimade/lib/python3.8/site-packages/optimade/server/config.py:167: UserWarning: Unable to find config file in default location /home/sadorf/.optimade.json, using the built-in default settings instead.
  warnings.warn(
WARNING:  [optimade] Log files are not saved.

    This is usually due to not being able to access a specified log folder or write to files
    in the specified log location, i.e., a `PermissionError` has been raised.

    To solve this, either set the OPTIMADE_LOG_DIR environment variable to a location
    you have permission to write to or create the /var/log/optimade folder, which is
    the default logging folder, with write permissions for the Unix user running the server.

INFO:     [optimade] Using: Mock MongoDB (mongomock)
An exception (KeyError) happened while trying to initialize 'optimade':
'structures'
```
Similar error in combination with "optimade run":
```
$ aiida-optimade -p optimade run
INFO:     Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:     Started reloader process [16410] using statreload
/home/sadorf/miniconda3/envs/aiida-optimade/lib/python3.8/site-packages/optimade/server/config.py:167: UserWarning: Unable to find config file in default location /home/sadorf/.optimade.json, using the built-in default settings instead.
  warnings.warn(
WARNING:  [optimade] Log files are not saved.

    This is usually due to not being able to access a specified log folder or write to files
    in the specified log location, i.e., a `PermissionError` has been raised.

    To solve this, either set the OPTIMADE_LOG_DIR environment variable to a location
    you have permission to write to or create the /var/log/optimade folder, which is
    the default logging folder, with write permissions for the Unix user running the server.

INFO:     [optimade] Using: Mock MongoDB (mongomock)
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/sadorf/miniconda3/envs/aiida-optimade/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/sadorf/miniconda3/envs/aiida-optimade/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sadorf/miniconda3/envs/aiida-optimade/lib/python3.8/site-packages/uvicorn/subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "/home/sadorf/miniconda3/envs/aiida-optimade/lib/python3.8/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/sadorf/miniconda3/envs/aiida-optimade/lib/python3.8/site-packages/uvicorn/main.py", line 397, in serve
    config.load()
  File "/home/sadorf/miniconda3/envs/aiida-optimade/lib/python3.8/site-packages/uvicorn/config.py", line 278, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/sadorf/miniconda3/envs/aiida-optimade/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/sadorf/miniconda3/envs/aiida-optimade/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/sadorf/local/aiida-optimade/aiida_optimade/main.py", line 30, in <module>
    from aiida_optimade.routers import (
  File "/home/sadorf/local/aiida-optimade/aiida_optimade/routers/structures.py", line 24, in <module>
    STRUCTURES = AiidaCollection(StructureData, StructureResource, StructureMapper)
  File "/home/sadorf/local/aiida-optimade/aiida_optimade/entry_collections.py", line 42, in __init__
    self.provider_fields = CONFIG.provider_fields[resource_mapper.ENDPOINT]
KeyError: 'structures'
```

**Comment by CasperWA** [comment]
Thanks for the report. This seems to be an issue of the implementation not properly retrieving configuration options if not explicitly defined.
